---
title: "RL Circuits"
date: "November 8th, 2020"
output: pdf_document
---

# Basics of RL Circuits

## Quick Facts 
* Energy stored in an inductor will increase over time as current flows through a RL circuit.
* Current will be equal to current of the battery as $t$ approaches infinity.
* Current will increase over time when switch is closed

## Important tendencies to note

For the context of the next bullet points, imagine there is an RL circuit with a switch. Here are some important tendencies to note:

* Suppose the switch is initially open. When the switch is closed, current will flow through the circuit. The inductor, though, will resist a change in current. What does this mean? Effectively, this means **when the switch is initially closed ($t=0$), we can imagine no current goes through the inductor.**
    + As $t$ approaches $\infty$, the inductor acts as a wire (no resistance).

## Formula Reference

FORMULA: Time constant of RL Circuit

$$\tau = \frac{L}{R}$$


FORMULA: Current of RL Circuit

$$I = I_{0}(1 - e^{\frac{-t}{\tau}})$$

## Useful Resources

* [The Physics LibreText](https://phys.libretexts.org/Bookshelves/University_Physics/Book%3A_University_Physics_(OpenStax)/Map%3A_University_Physics_II_-_Thermodynamics_Electricity_and_Magnetism_(OpenStax)/14%3A_Inductance/14.05%3A_RL_Circuits#:~:text=R%3D0.50A.-,From%20Equation%2014.5.,e%E2%88%92t%2F%CF%84L.)
* [van Biezen Analysis](https://www.youtube.com/watch?v=_W3p2euSH5Q)
