---
title: "Diffraction"
date: "February 21st, 2021"
output: pdf_document
---

## Formulas

Minima for diffraction of single slit:

$$
a sin \theta = m \lambda
$$

Where:

* $m$ = 1, 2, 3...
* $\lambda$ is wavelength
* $\theta$ is the separation angle
* $a$ is the slit width

Intensity of the diffraction pattern for single slit diffraction for an angle $\theta$ is:

$$
I( \theta ) = I_{m} ( \frac{ sin \alpha }{ \alpha } )^{2}
$$

Where:

* $I_{m}$ is the intensity at the center of the pattern
* $$
\alpha = \frac{\pi a}{\lambda} sin \theta
$$

Rayleigh's criterion:

$$
\theta_{R} = 1.22 \frac{ \lambda }{d}
$$

Where:

* $d$ is the diameter of the aperture through which the light passes.

Notes:

* Suggests two objects are on the verge of resolvability if the central diffraction maximum of one is at the first minimum of the other


For identical slits (double slits in this case) with width $a$ and center-to-center separation $d$, the intensity in the pattern varies with the angle $\theta$ from the central axis as:

$$
I( \theta ) = I_{m} ( cos^{2} \beta ) (\frac{sin \alpha}{ \alpha })^{2}
$$

Where:

* $I_{m}$ is the intensity at the center of the pattern
* $$
  \beta = ( \frac{\pi d}{\lambda} ) sin \theta
$$
* $$
  \alpha = ( \frac{\pi a}{\lambda} ) sin \theta
$$

Diffraction by multiple slits ($N$) results in maxima (lines) at angles $\theta$ such that

$$
d sin \theta = m \lambda
$$

Where:

* $m$ = 0, 1, 2, ...

A line's half-width is the angle from its center to the point where it disappears into the darkness and is given by:

$$
\Delta \theta_{hw} = \frac{ \lambda }{ N d cos \theta }
$$

Dispersion $D$ of a diffraction grating:

$$
D = \frac{\Delta \theta}{\Delta \lambda} = \frac{m}{d cos \theta}
$$

Notes:

* Dispersion of a diffraction grating is the measure of the angular separation $\Delta \theta$ of the lines it produces for two wavelengths differing by $\lambda$.
* $m$ is the order number
* $\theta$ is the angle

Resolving power $R$ of a diffraction grating is a measure of its ability to make the emission lines of two close wavelengths distinguishable. For two wavelengths differing by $\Delta \lambda$ and with an average value of $\lambda_{avg}$, the resolving power is given by:

$$
R = \frac{\lambda_{avg}}{\Delta \lambda} = N m
$$

For x rays of wavelength $\lambda$ scattering from crystal planes with separation $d$, the angles $\theta$ at which the scattered intensity is maximum are given by:

$$
2 d sin \theta = m \lambda
$$

## Problems

## Problem 5

This problem is regarding **single-slit diffraction**.

> A single slit is illuminated by light of wavelengths $\lambda_{a}$ and $\lambda_{b}$, chosen so that the first diffraction minimum of the $\lambda_{a}$ component coincides with the second minimum of the $\lambda_{b}$ component.
> 
> * If $\lambda_{b}$ = 350 nm, what is $\lambda_{a}$?
> * For what order number $m_{b}$ (if any) does a minimum of the $\lambda_{b}$ component coincide with the minimum of the $\lambda_{a}$ component in the order number:
>   * $m_{a}$ = 2
>   * $m_{a}$ = 3

We know that

$$
a sin \theta = m \lambda
$$

Since the first order diffraction minimum $m = 1$ of $\lambda_{a}$ coincides with the second order diffraction minimum $m = 2$ of $\lambda_{b}$, we can simply set them equal to each other:

$$
2 * \lambda_{b} = 1 * \lambda_{a}
$$

$$
\lambda_{a} = 2 * \lambda_{b}
$$

$$
\lambda_{a} = 2 * 350
$$

Thus, our answer for part a is $700$ nm.

For b and c, we can simply multiply constants to this:

$$
\lambda_{a} = 2 * \lambda_{b}
$$

$$
2 * \lambda_{a} = 2 * 2 * \lambda_{b}
$$

Thus, our answer is $4$ for part b.

$$
3 * \lambda_{a} = 3 * 2 * \lambda_{b}
$$

Thus, our answer is $6$ for part c.

## Problem 15

This problem is regarding **intensity in single-slit diffraction**.

> See book for question

Part A:

$$
I( \theta ) = I_{m} * ( \frac{ sin \alpha }{ \alpha } )^{2}
$$

$$
\frac{1}{2} = ( \frac{ sin \alpha }{ \alpha } )^{2}
$$

$$
\frac{1}{2} = ( \frac{ sin^{2} \alpha }{ \alpha^{2} } )
$$

$$
\frac{\alpha^{2}}{2} = sin^{2} \alpha
$$

Part B:

$$
\frac{1.39^{2}}{2} = sin^{2} ( 1.39 )
$$

This indeed holds true so 1.39 radians is a solution

Part C:

$$
\alpha = \frac{\pi a}{\lambda} sin \theta
$$

$$
\theta = sin^{-1} \frac{\lambda \alpha}{\pi a}
$$

$$
\theta = sin^{-1} \frac{0.442 \lambda}{a}
$$

Note:

$$
\Delta \theta = 2 \theta
$$

So:

$$
\Delta \theta = 2 sin^{-1} \frac{0.442 \lambda}{a}
$$

Part D:

$$
2 sin^{-1} \frac{0.442}{1}
$$

Thus, our answer is $52.5^{\circ}$

Part E:

$$
2 sin^{-1} \frac{0.442}{5}
$$

Thus, our answer is $10.1^{\circ}$

Part F:

$$
2 sin^{-1} \frac{0.442}{10}
$$

Thus, our answer is $5.06^{\circ}$

## Problem 23

This problem is regarding **diffraction by a circular aperture**.

> The two headlights of an approaching automobile are 1.4 m apart. At what 
> 
> * angular separation and maximum distance will the eye resolve them?
> 
> Assume that the pupil diameter is 5.0 mm, and use a wavelength of 550 nm for the light. Also assume that diffraction effects alone limit the resolution so that Rayleigh's criterion can be applied.

Apply Rayleigh's criterion:

$$
\theta_{R} = 1.22 \frac{\lambda}{d}
$$

$$
\theta_{R} = 1.22 \frac{550 \times 10^{-9}}{5.0 \times 10^{-3}}
$$

Thus, $\theta_{R} = 1.3 \times 10^{-4}\text{ radians}$, our answer

$sin$ is the ratio of separation to the maximum distance, so we can use this to solve for the distance:

$$
\frac{d_{h}}{L} = 1.22 \frac{\lambda}{d}
$$

$$
L = \frac{d_{h}}{1.22 \frac{\lambda}{d}}
$$


We know $d_{h}$ and we just calculated the angle, so we can solve for $L$. $L$ comes out to be 10432.19m, our answer.

## Problem 35

This problem is regarding **diffraction by a double slit**.

> Suppose that the central diffraction envelope of a double-slit diffraction pattern contains 11 bright fringes and the first diffraction minima eliminate (are coincident with) bright fringes. How many bright fringes lie between the first and second minima of the diffraction envelope?

For this question, we first use $m = \frac{d}{a}$:

$$
d sin \theta = 11 \lambda
$$

For the second diffraction minimum:

$$
a sin \theta = 2 \lambda
$$

So:

$$
\frac{d}{a} = \frac{11}{2}
$$

This represents the lower bound, so m has to be greater than 5.


$\frac{d}{a} = \frac{2 * 11}{2}$ represents the upper bound, so m has to be less than 11. This leaves 6 - 10, which is 5 bright fringes, our answer.

## Problem 45

This problem is regarding **diffraction gratings**.

> A diffraction grating 20.0 mm wide has 6000 rulings. Light of wavelength 589 nm is incident perpendicularly on the grating. What are the
> 
> * largest
> * second largest
> * third largest values of $\theta$ at which maxima appear on a distant viewing screen?

First, find $d$ by divding the grating length over the number of slits: $\frac{20 \times 10^{-3}}{6000}$.

Now, we know the the maximum value of $sin \theta$ is 1, so we can say that:

$$
\frac{m \lambda}{d} < 1
$$

The max value of $m$ is thus 5, since we have $\lambda$ and $d$.

The largest value of $\theta$ is then:

$$
sin \theta = \frac{(5 * (589 * 10^{-9}))}{3.33 \times 10^{-6}}
$$

$\theta$ comes out to be $62.1^{\circ}$

Repeat this for $m$ values 4 and 3 for part b and c respectively:

The second largest value of $\theta$ is then $45.0^{\circ}$

The third largest value of $\theta$ is then $32.0^{\circ}$

## Problem 55

This problem is regarding **dispersion and resolving power**.

> A source containing a mixture of hydrogen and deuterium atoms emits red light at two wavelengths whose mean is 656.3 nm and whose separation is 0.180 nm. Find the minimum number of lines needed in a diffraction grating that can resolve these lines in the first order.

For this question, we can use:

$$
R = \frac{\lambda_{avg}}{\Delta \lambda} = N m
$$

Solve for $N$:

$$
N = \frac{\lambda_{avg}}{m \Delta \lambda}
$$

We know:

* $m = 1$
* $\lambda_{avg} = 656.3\text{ nm}$
* $\Delta \lambda = 0.180\text{ nm}$

So:

$$
N = \frac{656.4}{1 * 0.180}
$$

This comes out to be 3646 lines, our answer.

## Problem 63

This problem is regarding **dispersion and resolving power**.

> Assume that the limits of the visible spectrum are arbitrarily chosen as 430 and 680 nm. Calculate the number of rulings per millimeter of a grating that will spread the first-order spectrum through an angle of $20.0^{\circ}$.

We know:

$$
\lambda_{l} = d sin \theta
$$

$$
\lambda_{h} = d sin ( \theta + \Delta \theta )
$$

Now, we need to solve for $d$, the distance between the slits.

Consider what $sin ( \theta + \Delta \theta )$ can expand to using an identity:

$$
sin ( \theta + \Delta \theta ) = sin \theta cos ( \Delta \theta ) + cos \theta sin ( \Delta \theta )
$$

Goal is to get rid of the $\theta$ so we remain with $\Delta \theta$

We can substitute occurrences of $sin \theta$ with $\frac{\lambda_{l}}{d}$

$$
\frac{\lambda_{l}}{d} cos ( \Delta \theta ) + cos ( \theta ) sin ( \Delta \theta )
$$

We still have a $cos \theta$, but we can also substitute this with $\sqrt{1 - sin^{2} \theta}$. We can now express $\lambda_{h}$ as:

$$
\lambda_{h} = d ( \frac{\lambda_{l}}{d} cos ( \Delta \theta ) + \sqrt{1 - \frac{\lambda_{l}^{2}}{d^{2}}} sin ( \Delta \theta ) )
$$

We can multiply the $d$ to each term:

$$
\lambda_{h} = \lambda_{l} cos ( \Delta \theta ) + \sqrt{d^{2} - \lambda_{l}^{2}} sin ( \Delta \theta ) )
$$

Now, there are no occurrences of $\theta$, we can solve for $d$:

$$
d = \sqrt{( \frac{\lambda_{h} - \lambda_{l} * cos ( \Delta \theta )}{sin ( \Delta \theta )} )^{2} + \lambda_{l}^{2}}
$$

We have all parameters in this expression, so we can solve for $d$, which comes out to be 914 nm.

We can find the number of rulings per millimeter, by doing $\frac{1}{914 \times 10^{-6}}$, since we can assume the slit width is extremely small.

This comes out to be 1094 rulings/mm, our answer.
