---
title: "Relativity"
date: "March 2nd, 2021"
output: pdf_document
---

## Formulas

### Time Dilation

$$
\Delta t = \frac{\Delta t_{0}}{\sqrt{1 - (\frac{v}{c})^{2}}} = \frac{\Delta t_{0}}{\sqrt{1 - \beta^{2}}} = \gamma \Delta t_{0}
$$

Where:

* $\Delta t$ is observed time interval
* $\Delta t_{0}$ is actual time interval
* $v$ is the relative speed between the two frames
* $c$ speed of light
* $\beta = \frac{v}{c}$, called the speed parameter
* $\gamma = \frac{1}{\sqrt{1 - \beta^{2}}}$. called the Lorentz factor

### Length Contraction

$$
L = L_{0} \sqrt{1 - \beta^{2}} = \frac{L_{0}}{\gamma}
$$

### Lorentz Transformation Equations

These relate the spacetime coordinates of a single event as seen by two observers in two inertial frames, $S$ and $S'$. $S'$ is moving relative to $S$ with velocity $v$ in the positive $x$ and $x'$ direction. The four coordinates are related by:

$$
x' = \gamma (x - vt)
$$

$$
y' = y
$$

$$
z' = z
$$

$$
t' = \gamma (t - \frac{vx}{c^{2}})
$$

### Doppler Effect for Light

$$
\lambda = \lambda_{0} \sqrt{\frac{1 + \beta}{1 - \beta}}
$$

Where:

* **The separation is increasing** between the detector and source
  * **If the separation is decreasing**, flip the signs in both the numerator and denominator
* $\beta = \frac{v}{c}$, where $v$ is the relative radial speed (along a line through the source and detector)

For speeds that are much lower than $c$ ($v \ll c$), the magnitude of the wavelength shift from the Doppler effect is approximately related to $v$ by:

$$
v = \frac{\lvert \Delta \lambda \rvert}{\lambda_{0}} c
$$

If the relative motion of the light source is **perpendicular** to a line through the source and detector, the frequency $f$ is related to the proper frequency $f_{0}$ by:

$$
f = f_{0} \sqrt{1 - \beta^{2}}
$$

### Momentum and Energy

Definitions of linear momentum, energy, and kinetic energy of a particle of mass $m$:

Momentum:

$$
\vec{p} = \gamma m \vec{v}
$$

Energy:

$$
E = m c^{2} + K = \gamma m c ^{2}
$$

Kinetic Energy:

$$
K = mc^{2} ( \gamma - 1 )
$$

Where:

* $\gamma$ is the Lorentz factor
* $mc^{2}$ is the mass energy or rest energy associated with the mass of the particle

From these equations:

$$
( p c )^{2} = K^{2} + 2 K m c^{2}
$$

$$
E^{2} = ( p c )^{2} + ( m c^{2} )^{2}
$$

When a system undergoes a chemical or nuclear reaction, the $Q$ of the reaction is the negative of the change in the system's total mass energy:

$$
Q = M_{i} c^{2} + M_{f} c^{2} = - \Delta M c^{2}
$$

Where:

* $M_{i}$ is the system's total mass before the reaction
* $M_{f}$ is the system's total mass after the reaction

## Special Theory of Relativity

Two Postulates:

* The laws of physics are the same for observers in all inertial reference frames.
* The speed of light in vacuum has the same value $c$ in all directions and in all inertial reference frames.

If two observers are in relative motion, they generally will **not agree** as to whether two events are simultaneous.

Time Dilation: When two successive events occur at the same place in an inertial reference frame, observers moving relative to the frame will observe the time interval between the events (actual measured by a single clock: $\Delta t_{0}$) (the proper time between them) as a larger value than it actually is (observed: $\Delta t$)

## Relativity of Length

The length $L_{0}$ of an object (at rest) measured by an observer in an inertial reference frame is known as the proper length.

Length Contraction: Observers in frames moving relative to that frame and **parallel** to the length will always measure a **shorter length**.

## Relativity of Velocities

When a particle is moving with speed $u'$ in the positive $x'$ direction in an inertial reference frame $S'$ that itself is moving with speed $v$ parallel to the $x$ direction of a second inertial reference frame $S$, the speed $u$ of the particle **as measured in $S$** is:

$$
u = \frac{u' + v}{1 + \frac{u' v}{c^{2}}}
$$

## Problems

## Problem 1

This problem is regarding **simultaneity and time dilation**.

> The mean lifetime of stationary muons is measured to be 2.2000 $\mu$s. The mean lifetime of high-speed muons in a burst of cosmic rays observed from Earth is measured to be 16.000 $\mu$s. To five significant figures, what is the speed parameter $\beta$ of these cosmic-ray muons relative to Earth?

For this question, we need to find the speed parameter given the observed time due to time dilation. We can find this using:

$$
\Delta t = \frac{\Delta t_{0}}{\sqrt{1 - \beta^{2}}}
$$

We solve for $\beta$:

$$
\beta = \sqrt{-1 * ( ( \frac{\Delta t_{0}}{\Delta t} )^{2} - 1 )}
$$

Doing the calculations, this comes out to be $0.99050$, our answer.

## Problem 2

This problem is regarding **simultaneity and time dilation**.

> To eight significant figures, what is the speed parameter $\beta$ if the Lorentz factor $\gamma$ is:
> 
> * 1.0100000
> * 10.000000
> * 100.00000
> * 1000.0000

We know the Lorentz factor can be expressed in terms of $\beta$ by the following:

$$
\gamma = \frac{1}{\sqrt{1 - \beta^{2}}}
$$

So, we solve for $\beta$:

$$
\beta = \sqrt{1 - \frac{1}{\gamma^{2}}}
$$

Thus, our answers are:

* $\beta = 0.14037076$
* $\beta = 0.99498744$
* $\beta = 0.99995000$
* $\beta = 0.99999950$

For a, b, c, d, respectively.

## Problem 5

This problem is regarding **simultaneity and time dilation**.

> An unstable high-energy particle enters a detector and leaves a track of length 1.05 mm before it decays. Its speed relative to the detector was 0.992c. What is its proper lifetime? That is, how long would the particle have lasted before decay had it been at rest with respect to the detector?

We need to find the actual time instead of the observed time due to time dilation:

$$
\Delta t = \frac{\Delta t_{0}}{\sqrt{1 - \beta^{2}}}
$$

$$
\Delta t_{0} = \Delta t \sqrt{1 - \beta^{2}}
$$

The observed time can be found by taking the relative distance traveled over the relative speed:

$$
t = \frac{d}{v}
$$

Thus:

$$
\Delta t_{0} = \frac{1.05}{0.992 * 3 \times 10^{8}} \sqrt{1 - (0.992)^{2}}
$$

This comes out to be 0.446 picoseconds, our answer.

## Problem 10

This problem is regarding **the relativity of length**.

> A meter stick in frame S' makes an angle of $30^{\circ}$ with the x' axis. If that frame moves parallel to the x axis of frame S with speed 0.90c relative to frame S, what is the length of the stick as measured from S?

Since the frame is only moving parallel to the x axis, we know the y component won't change but the x component will. We can figure out the length contraction of the x component with:

$$
L_{x} = L_{0} cos \theta \sqrt{1 - \beta^{2}}
$$

$$
L_{x} = \sqrt{L_{0}^{2} (cos \theta)^{2} - L_{0}^{2} (cos \theta)^{2} \beta^{2}}
$$

$$
L_{x} = \sqrt{L_{0}^{2} (cos \theta)^{2} - L_{0}^{2} (cos \theta)^{2} (\frac{v}{c})^{2}}
$$

$$
L_{x} = \sqrt{L_{0}^{2} (cos \theta)^{2} - L_{0}^{2} (cos \theta)^{2} (\frac{v}{c})^{2}}
$$

We know the total length in terms of its components is given by:

$$
L = \sqrt{L_{x}^{2} + L_{y}^{2}}
$$

And then we can expand:

$$
L = \sqrt{(\sqrt{L_{0}^{2} (cos \theta)^{2} - L_{0}^{2} (cos \theta)^{2} (\frac{v}{c})^{2}})^{2} + (L_{0} * sin \theta)^{2}}
$$

$$
L = \sqrt{L_{0}^{2} (cos \theta)^{2} - L_{0}^{2} (cos \theta)^{2} (\frac{v}{c})^{2} + (L_{0}^{2} * (sin \theta)^{2})}
$$

$$
L = \sqrt{L_{0}^{2} cos^{2} \theta - L_{0}^{2} cos^{2} \theta (\frac{v}{c})^{2} + L_{0}^{2} sin^{2} \theta}
$$

Notice via the $cos^{2} \theta + sin^{2} \theta = 1$ identity we can simplify this to:

$$
L = \sqrt{L_{0}^{2} - L_{0}^{2} cos^{2} \theta (\frac{v}{c})^{2}}
$$


$$
L = \sqrt{L_{0}^{2} * (1 - cos^{2} 30 (0.90)^{2})}
$$

$$
L = \sqrt{L_{0}^{2} * (1 - cos^{2} 30 (0.90)^{2})}
$$

Thus, we can represent $L$ in terms of $L_{0}$ by the following:

$$
L = \sqrt{L_{0}^{2} * (0.3925)}
$$

For a meter stick, we know $L_{0}$ is just 1m, so $L = 0.63$m, our answer.

## Problem 11

This problem is regarding **the relativity of length**.

> A rod lies parallel to the x axis of reference frame S, moving along the axis at a speed of 0.630c. Its rest length is 1.70m. What will be its measured length in frame S? 

For this question, we simply use the length contraction formula:

$$
L = L_{0} * \sqrt{1 - \beta^{2}}
$$

$$
L = 1.70 * \sqrt{1 - (0.630^{2})}
$$

Thus, our answer is 1.32m.

## Problem 19

This problem is regarding **the Lorentz transformation**.

> An experimenter arranges to trigger two flashbulbs simultaneously, producing a big flash located at the origin of his reference frame and a small flash at x = 30.0 km. An observer moving at a speed of 0.250c in the positive direction of x also views the flashes.
>
> * What is the time interval between them according to her?
> * Which flash does she say occurs first?


Let us say the time the big flash happened was $t_{b}$ and the time the small flash happened was $t_{s}$. The difference between these two we can say is $\Delta t$:

$$
\Delta t = t_{s} - t_{b}
$$

We know this difference is 0 for the experimenter. In other words: $t_{s} = t_{b}$. But let us find the time difference for the observer, which is:

$$
\Delta t = t'_{s} - t'_{b}
$$

We can represent this through Lorentz's transformation equation:

$$
\Delta t = t'_{s} - t'_{b}
$$

$$
\Delta t = \gamma ( t_{s} - \frac{v * x_{s}}{c^{2}} ) - \gamma ( t_{b} - \frac{v * x_{b}}{c^{2}} )
$$

Since we know $t_{s} = t_{b}$:

$$
\Delta t = \gamma ( \frac{v * x_{b}}{c^{2}} - \frac{v * x_{s}}{c^{2}} )
$$

$$
\Delta t = \gamma ( \frac{v * x_{b} - v * x_{s}}{c^{2}} )
$$

$$
\Delta t = \gamma ( \frac{v (x_{b} - x_{s})}{c^{2}} )
$$

Substitute in the Lorentz factor:

$$
\Delta t = \frac{1}{\sqrt{1 - \frac{v}{c^{2}}}} \frac{v (x_{b} - x_{s})}{c^{2}}
$$

Putting in the values:

$$
\Delta t = \frac{0.250c (0 - 30)}{c^{2}}
$$

$$
\Delta t = \frac{1}{\sqrt{1 - \frac{(0.250c)^{2}}{c^{2}}}} \frac{0.250c (0 - 30)}{c^{2}}
$$

$$
\Delta t = \frac{1}{\sqrt{1 - 0.0625}} \frac{0.250 * -30}{c}
$$

Convert 30 into 30000 for m/s:

$$
\Delta t = \frac{1}{\sqrt{1 - 0.0625}} \frac{0.250 * -30000}{c}
$$

$$
\Delta t = \frac{0.250 * -30000}{c * \sqrt{1 - 0.0625}}
$$

Our answer comes out to be $\Delta t = 25.8 \mu \text{s}$. The calculation I performed resulted in a negative time interval, which means that $t'_{s}$ was smaller than $t'_{b}$. That means the observer noticed the small flash occurred first.

## Problem 23

This problem is regarding **the Lorentz transformation**.

> A clock moves along an x axis at a speed of 0.600c and reads zero as it passes the origin of the axis.
> 
> * Calculate the clock’s Lorentz factor.
> * What time does the clock read as it passes x = 180 m?

We know the relative speed, so we can find the Lorentz factor:

$$
\gamma = \frac{1}{\sqrt{1 - ( \frac{v}{c} )^{2}}}
$$

$$
\gamma = \frac{1}{\sqrt{1 - ( \frac{0.600c}{c} )^{2}}}
$$

$$
\gamma = \frac{1}{\sqrt{1 - ( 0.36 )}}
$$

$$
\gamma = \frac{1}{\sqrt{0.64}}
$$

$$
\gamma = 1.25
$$

Thus, $\gamma = 1.25$ is our answer.

Now, we can find the time:

$$
t' = \gamma (t - \frac{vx}{c^{2}})
$$

We already have the Lorentz factor from the first part of this question, and we have the speed and distance:

$$
t' = 1.25 * (t - \frac{0.6 * 180}{3 \times 10^{8}})
$$

We can represent $t$ as $\frac{d}{v}$:

$$
t' = 1.25 * ((\frac{180}{0.6 * c}) - \frac{0.6 * 180}{3 \times 10^{8}})
$$

Solving this, we get $t' = 0.800 \mu \text{s}$, our answer.

## Problem 27

This problem is regarding **the relativity of velocities**.

> A particle moves along the x' axis of frame S' with velocity 0.40c. Frame S' moves with velocity 0.60c with respect to frame S. What is the velocity of the particle with respect to frame S?

For this, we use the relativity of velocities formula:

$$
u = \frac{u' + v}{1 + \frac{u' v}{c^{2}}}
$$

$$
u = \frac{0.6c + 0.4c}{1 + \frac{0.24 c^{2}}{c^{2}}}
$$

$$
u = \frac{c}{1 + 0.24}
$$

$$
u = \frac{c}{1 + 0.24}
$$

$$
u = c * \frac{1}{1 + 0.24}
$$

Thus, our answer is that the velocity of the particle with respect to frame S is:

$$
u = 0.81c
$$

## Problem 35

This problem is regarding **the doppler effect for light**.

> A spaceship, moving away from Earth at a speed of 0.900c, reports back by transmitting at a frequency (measured in the spaceship frame) of 100 MHz. To what frequency must Earth receivers be tuned to receive the report?

For this question, we use the Doppler effect for light:

$$
\lambda = \lambda_{0} \sqrt{\frac{1 + \beta}{1 - \beta}}
$$

We have frequency, and we know $\lambda = \frac{1}{f}$, so invert expression:

$$
f = \frac{1}{\lambda_{0} \sqrt{\frac{1 + \beta}{1 - \beta}}}
$$

$$
f = \frac{1}{\lambda_{0} \sqrt{\frac{1 + 0.9}{1 - 0.9}}}
$$

$$
f = \frac{1}{\lambda_{0}} * \frac{1}{\sqrt{\frac{1 + 0.9}{1 - 0.9}}}
$$

$$
f = 100 * \frac{1}{\sqrt{\frac{1 + 0.9}{1 - 0.9}}}
$$

This comes out to be `22.9 MHz`, our answer.

## Problem 36

This problem is regarding **the doppler effect for light**.

> Certain wavelengths in the light from a galaxy in the constellation Virgo are observed to be 0.4% longer than the corresponding light from Earth sources.
> 
> * What is the radial speed of this galaxy with respect to Earth?
> * Is the galaxy approaching or receding from Earth?

We know that:

$$
\lambda = \lambda_{0} \sqrt{\frac{1 + \beta}{1 - \beta}} = 1.004 * \lambda_{0}
$$

So, solve for $\beta$:

$$
\lambda_{0} \sqrt{\frac{1 + \beta}{1 - \beta}} = 1.004 * \lambda_{0}
$$

$$
\sqrt{\frac{1 + \beta}{1 - \beta}} = 1.004
$$

$$
\frac{1 + \beta}{1 - \beta} = (1.004)^{2}
$$

$$
1 + \beta = (1.004)^{2} (1 - \beta)
$$

$$
1 + \beta = (1.004)^{2} - (1.004)^{2} \beta
$$

$$
1 + \beta = (1.004)^{2} - (1.004)^{2} \beta
$$

$$
(1 + (1.004)^{2}) \beta = (1.004)^{2} - 1
$$

$$
\beta = \frac{(1.004)^{2} - 1}{(1 + (1.004)^{2})}
$$

Thus, we find $\beta = 0.004c$, our answer. We can tell that the galaxy is **receding** from Earth because the wavelength is getting longer, which the formula implies can only happen when the distance is increasing.

## Problem 41

This question is regarding **momentum and energy**.

> The mass of an electron is $9.10938188 \times 10^{-31}$ kg. To six significant figures, find
> 
> * $\gamma$
> * $\beta$ for an electron with kinetic energy K = 100.000 MeV

For this question, we can express the kinetic energy using:

$$
K = m c^{2} * ( \gamma - 1 )
$$

We solve for $\gamma$:

$$
\gamma = \frac{K}{m * c^{2}} + 1
$$

Using $1.602177 \times 10^{-19}$ to convert from eV to Joules

$$
\gamma = \frac{100 * 10^{6} * 1.602177 * 10^{-19}}{9.10938188 \times 10^{-31} * (2.99792458 \times 10^{8})^{2}} + 1
$$

Thus, our answer is:

$$
\gamma = 196.695
$$

Since we have found $\gamma$, the Lorentz factor, we can find the speed parameter by the definition:

$$
\gamma = \frac{1}{\sqrt{1 - \beta^{2}}}
$$

$$
\sqrt{1 - \beta^{2}} = \frac{1}{\gamma}
$$

$$
\beta = \sqrt{-1 * (\frac{1}{\gamma^{2}} - 1)}
$$

$$
\beta = \sqrt{-1 * (\frac{1}{\gamma^{2}} - 1)}
$$

Thus, we find $\beta = 0.999987$, our answer.

## Problem 47

This question is regarding **momentum and energy**.

> A 5.00-grain aspirin tablet has a mass of 320 mg. For how many kilometers would the energy equivalent of this mass power an automobile? Assume 12.75 km/L and a heat of combustion of $3.65 \times 10^{7}$ J/L for the gasoline used in the automobile.

First, convert 320mg to kg:

$$
320 * 10^{-6}\text{ kg}
$$

Now, we find the rest energy:

$$
E = 320 * 10^{-6} * (3 \times 10^{8})^{2}
$$

Then, we find the amount of liters from the heat of combustion:

$$
L = \frac{320 * 10^{-6} * (3 \times 10^{8})^{2}}{3.65 \times 10^{7}}
$$

Then, we multiply by the amount of kilometers that can be traveled per liter:


$$
km = \frac{320 * 10^{-6} * (3 \times 10^{8})^{2}}{3.65 \times 10^{7}} * 12.75
$$

This comes out to be $1.01 \times 10^{7}\text{ km}$, our answer.
