---
title: "LC & RLC Circuits"
date: "November 10th, 2020"
output: pdf_document
---

## LC Circuit

An LC circuit is composed of an **inductor** and a **capacitor**. A capacitor stores energy in an electric field between its plates, and an inductor stores energy in its magnetic field.

Suppose an inductor was connected to a charged capacitor in a circuit. First, the capacitor would drive a current through an inductor because of the voltage across the capacitor. The inductor builds up a magnetic field from the current flow. After the voltage comes to 0 for the capacitor, the built up magnetic field starts to induce a voltage in the coil since it tries to resist the change in current. The induced voltage causes a current to flow in the opposite direction, and the capacitor starts to recharge, with a voltage of opposite polarity. Over time, this will produce an oscillating effect, where the energy is traded between the capacitor and inductor. In an ideal circuit with no resistance, this means the oscillating energy would go on forever, however, in practical purposes there is always internal resistance which makes the oscillations die out.

## RLC Circuit

A RLC circuit is composed of a resistor, inductor, and capacitor either in series or parallel. This note section will concern it self with the **series RLC circuits**. A RLC circuit is like an LC circuit in that it has that property of resonance. Though, the oscillation dies out quicker because of the resistor.

The formulas in this section for RLC circuits will be for series RLC circuits.

## Formulas

Current of an LC circuit:

$$
i = \pm \frac{1}{\sqrt{LC}} \sqrt{Q^{2} - q(t)^{2}}
$$

This can be derived using Kirchoff's voltage law.

***

Charge in inductor of an LC circuit at time t:

$$
q(t) = Q cos( \omega t + \phi )
$$

***

Resonance frequency of LC / RLC circuit:

$$
f_{0} = \frac{\omega_{0}}{2 \pi}
$$

$$
\omega_{0} = \frac{1}{\sqrt{LC}}
$$

Notes:

* At the resonance frequency, the capacitive reactance is equal to the inductive reactance.

***

Capacitive Reactance for a capacitor in an AC circuit:

$$
X_{c} = \frac{1}{2 \pi f C}
$$

***

Inductive Reactance for a inductor in an AC circuit:

$$
X_{L} = 2 \pi f L
$$

***

Impedance (Measure of opposition from a circuit when voltage applied):

$$
Z = \sqrt{R^{2} + (X_{L} - X_{C})^{2}}
$$

***

RMS current (root mean square) current. This is the time-averaged voltage or current in an AC circuit.

$$
I_{rms} = \frac{V_{S}}{Z}
$$

Where:

* $V_{S}$ is the voltage of the source 
* $Z$ is the impedance.

***

Voltage of a RLC circuit

$$
V_{S} = \sqrt{V_{R}^{2} + (V_{L} - V_{C})^{2}}
$$

Where:

* $V_{R}$ is the voltage drop of the resistor 
* $V_{L}$ is the voltage drop of the inductor
* $V_{C}$ is the voltage drop of the capacitor

***

Power consumed by RLC circuit:

$$
P = I^{2} R
$$

Notes:

* Only the resistor in the RLC circuit consumes power
* So the power consumed by the circuit is just the power consumed by the resistor

***

Power consumed by RLC circuit (2):

$$
P = V_{rms} I_{rms} cos( \phi )
$$

Where:

* $cos( \phi )$ is equal to $\frac{R}{Z}$


## References

[LC Circuit - van Biezen](https://www.youtube.com/watch?v=b_79v4h9Y9s)

[LC Circuit - Wikipedia](https://en.wikipedia.org/wiki/LC_circuit)

[RLC Circuit - Wikiversity](https://en.wikiversity.org/wiki/RLC_circuit)

[Lumenlearning](https://courses.lumenlearning.com/boundless-physics/chapter/alternating-currents/)

[RLC Circuit Problem worked out](https://www.youtube.com/watch?v=2GvqQvohP2k)
