---
title: "Entropy and the Second Law of Thermodynamics"
date: "February 5th, 2021"
output: pdf_document
---

## Formulas

Entropy change $\Delta S$ for a reversible process that takes a system between the initial to final (or vice versa) state:

$$
\Delta S = S_{f} - S_{i} = \int_{i}^{f} \frac{dQ}{T}
$$

Where:

* $Q$ is the energy transferred as heat to or from the system during the process
* $T$ is the temperature of the system in kelvins during the process

For a reversible isothermal process:

$$
\Delta S = S_{f} - S_{i} = \frac{Q}{T}
$$

When the temperature change $\Delta T$ of a system is small relative to the temperature (in Kelvins) before and after the process, the entropy change can be approximated as:

$$
\Delta S = S_{f} - S_{i} \approx \frac{Q}{T_{avg}}
$$

Where:

* $T_{avg}$ is the system's average temperature during the process.

When an ideal gas (reversibly) changes from an initial state, with changes to temp and volume, the change in entropy of the gas is:

$$
\Delta S = S_{f} - S_{i} = nR ln \frac{V_{f}}{V_{i}} = n C_{v} ln \frac{T_{f}}{T_{i}}
$$

The second law of thermo is an extension of the entropy postulate: it states that if a process occurs in a closed system, the entropy of the system **increases for irreversible processes** and **remains constant for reversible processes**. Entropy of the system will **never decrease**. Meaning:

$$
\Delta S \geq 0
$$

Efficiency $\varepsilon$ of an engine:

$$
\varepsilon = \frac{\text{energy we get}}{\text{energy we pay for}} = \frac{\lvert W \rvert}{\lvert Q_{H} \rvert}
$$

Carnot engine efficiency

$$
\varepsilon_{C} = 1 - \frac{\lvert Q_{L} \rvert}{\lvert Q_{H} \rvert} = 1 - \frac{T_{L}}{T_{H}}
$$

Where:

* $T_{H}$ is the temperature of the high-temperature reservoir
* $T_{L}$ is the temperature of the low-temperature reservoir

Notes:

* Real Carnot engines always have an efficient lower than that of a Carnot engines. Even ideal engines that are not Carnot engines also have efficiencies that are lower than a Carnot engine
* A perfect engine is where we extract heat from a hot reservoir and convert it straight into work. Though, an engine like this would violate the second law of thermodynamics.

Coefficient of performance $K$ for a refrigerator:

$$
K = \frac{\text{what we want}}{\text{what we pay for}} = \frac{\lvert Q_{L} \rvert}{\lvert W \rvert}
$$

A Carnot refrigerator is a Carnot engine in reverse:

$$
K_{C} = \frac{\lvert Q_{L} \rvert}{\lvert Q_{H} \rvert - \lvert Q_{L} \rvert} = \frac{T_{L}}{T_{H} - T_{L}}
$$

The perfect refrigerator is when the energy extracted (as heat) from the low-temp reservoir is converted completely to heat _discharged_ to the high-temperature reservoir without the need to do any work. This would violate the second law of thermodynamics though.

For a system of $N$ molecules, that may be distributed between two halves of a box, the multiplicity is given by:

$$
W = \frac{N!}{n_{1}! n_{2}!}
$$

Where:

* $n_{1}$ is the number of molecules in one half of the box
* $n_{2}$ is the number of molecules in the other half

Multiplicity $W$ of a configuration fo a system and the entropy $S$ of the system in that configuration are related by Boltzmann's entropy equation:

$$
S = k ln W
$$

Where:

* $k = 1.38 \times 10^{-23}\text{ J/K}$ -- this is the Boltzmann constant

When $N$ is very large (the usual case), we can approximate $ln N!$ with Stirling's approximation:

$$
ln N! \approx N(ln N) - N
$$

## Problems

## Problem 3

This question is regarding **entropy**.

> A 2.50 mol sample of an ideal gas expands reversibly and isothermally at 360 K until its volume is doubled. What is the increase in entropy of the gas?

For this question we can use the following formula:

$$
\Delta S = n R ln \frac{V_{f}}{V_{i}}
$$

This formula applies because the change is reversible.

$$
\Delta S = 2.50 * 8.31 * ln 2 
$$

Thus, the answer is $14.4\text{ J/K}$

## Problem 7

This question is regarding **entropy**.

> A 50.0 g block of copper whose temperature is 400 K is placed in an insulating box with a 100 g block of lead whose temperature is 200 K.
> 
> * What is the equilibrium temperature of the two block system? 
> * What is the change in the internal energy of the system between the initial state and the equilibrium state?
> * What is the change in the entropy of the system? (See Table 18-3)

The equilibrium temperature can be found, since the energy transfer is net 0.

$$
m_{c} C_{c} (T_{F} - T_{1}) + m_{l} C_{l} (T_{F} - T_{2}) = 0
$$

Solving this for $T_{f}$, we find it to be `320 K`, our answer.

Given that this happens in an insulating box, the change in the internal energy of the _system_ is **zero**.

We can find the change in entropy using the following formula:

$$
m c ln (\frac{T_{f}}{T_{i}})
$$

Add the entropy changes for both components:

$$
m_{1} c_{1} ln (\frac{T_{f}}{T_{i1}}) + m_{2} c_{2} ln (\frac{T_{f}}{T_{i2}})
$$

$$
(50.0) (386) ln (\frac{320}{400}) + (100) (128) ln (\frac{320}{200})
$$

This comes out to be +1.72 J/K.

## Problem 23

This question is regarding **engines**.

> A Carnot engine whose low-temperature reservoir is at $17^{\circ}\text{ C}$ has an efficiency of 40%. By how much should the temperature of the high-temperature reservoir be increased to increase the efficiency to 50%?

First, we need to convert the temperature into Kelvin, $17 + 273.16 = 290.16\text{K}$. Next, we should determine what the temperature of the high-temperature reservoir is when the efficiency is 40%:

$$
\varepsilon = 1 - \frac{T_{C}}{T_{H}}
$$

$$
0.4 = 1 - \frac{290.16K}{T_{H}}
$$

$$
T_{H} = 483.6\text{K}
$$

We repeat this for when the efficiency is at 50%:

$$
0.5 = 1 - \frac{290.16K}{T_{H}}
$$

$$
T_{H} = 580.32\text{K}
$$

Then, we just subtract to find the difference to see the necessary increase:

$$
\Delta T = 580.32 - 483.6
$$

This comes out to be `97K`, our answer.

## Question 24

This question is regarding **engines**.

> A Carnot engine absorbs 52 kJ as heat and exhausts 36 kJ as heat in each cycle. Calculate:
> 
> * the engine’s efficiency
> * the work done per cycle in kilojoules.

To calculate the engine's efficiency, we can use the following:

$$
\varepsilon = 1 - \frac{\lvert Q_{L} \rvert}{\lvert Q_{H} \rvert}
$$

$$
\varepsilon = 1 - \frac{36\text{ kJ}}{52\text{ kJ}}
$$

Thus, our answer is $\varepsilon = 0.31$.

The work done per cycle of course is the change in energy, so we can just do:

$$
W = \lvert Q_{H} \rvert - \lvert Q_{L} \rvert
$$

This comes out to be `16 kJ`, our answer.

## Question 28

This question is regarding **engines**.

> In the first stage of a two-stage Carnot engine, energy is absorbed as heat $Q_{1}$ at temperature $T_{1}$, work $W_{1}$ is done, and energy is expelled as heat $Q_{2}$ at a lower temperature $T_{2}$. The second stage absorbs that energy as heat $Q_{2}$, does work $W_{2}$, and expels energy as heat $Q_{3}$ at a still lower temperature $T_{3}$. Prove that the efficiency of the engine is $(T_{1} - T_{3})/T_{1}$.

First:

$$
\varepsilon = \frac{\lvert W \rvert}{\lvert Q_{H} \rvert}
$$

We can express this as (for this problem):

$$
\varepsilon = \frac{(Q_{1} - Q_{2}) + (Q_{2} - Q_{3})}{Q_{1}}
$$

This simplifies to:

$$
\varepsilon = 1 - \frac{Q_{3}}{Q_{1}}
$$

Since we know the change in entropy is the same, we can determine:

$$
\varepsilon = 1 - \frac{T_{3}}{T_{1}}
$$

$$
\varepsilon = \frac{T_{1}}{T_{1}} - \frac{T_{3}}{T_{1}}
$$

Therefore:

$$
\varepsilon = \frac{T_{1} - T_{3}}{T_{1}}
$$

## Question 29

This question is regarding **engines**.

> See book for question and necessary figure

To solve for the work done, we need to determine the area under the curve:

$$
(2V_{0} - V_{0}) * (2 \rho_{0} - \rho_{0})
$$

$$
(V_{0}) * (\rho_{0}) 
$$

This comes out to be `2272.5 J`.

To compute the energy added as heat for stroke `abc`, we can just find $n C_{V} (T_{b} - T_{a}) + n C_{p} (T_{c} - T_{b})$. We know for a monatomic gas that $C_{v} = \frac{3}{2} R$ (constant volume), and $C_{p} = \frac{5}{2} R$ (constant pressure).

$T_{b} - T_{a} = T_{a}$ and $T_{c} - T_{b} = T_{b}$ because we know c is double of b is double of a via the ideal gas law. Here's where we are at:

$$
n (\frac{3}{2} R) T_{a} + n (\frac{5}{2} R) T_{b}
$$

We can rearrange this like so:

$$
\frac{3}{2} n RT_{a} + \frac{5}{2} nR T_{b}
$$

We also know $T_{b} = 2 T_{a}$, sp:

$$
\frac{3}{2} n R T_{a} + 5 nR T_{a}
$$

$$
\frac{13}{2} n R T_{a}
$$

Notice the $n R T_{a}$. This is just $p_{0} V_{0}$

$$
\frac{13}{2} p_{0} V_{0}
$$

This comes out to be 14771.25 J.

For part C, we simply divide the "energy we get" (the work calculated in A), by the "energy we pay for" (the energy added as heat in B):

$$
\frac{2272.5}{14771.25} = 0.154
$$

Thus, the efficiency of the cycle is 15.4%.

For part d, we know $T_{c} = 4 T_{a}$, as both pressure and volume go up by a factor of 2. Thus, the efficiency can be calculated:

$$
\varepsilon = 1 - \frac{T_{a}}{T_{c}}
$$

$$
\varepsilon = 1 - \frac{1}{4}
$$

Thus, our answer is $\varepsilon = 0.75$.

(Part E) This is greater than the efficiency in part C.

## Question 39

This question is regarding **refrigerators and real engines**.

> A Carnot air conditioner takes energy from the thermal energy of a room at $70^{\circ}\text{ F}$ and transfers it as heat to the outdoors, which is at $96^{\circ}\text{ F}$. For each joule of electric energy required to operate the air conditioner, how many joules are removed from the room?

This is a Carnot refrigerator. We can find its coefficient of performance which is the ratio of the "what we want" over the "what we pay for", which is what we are interested in. The efficiency for a Carnot refrigerator is:

$$
K_{C} = \frac{T_{L}}{T_{H} - T_{L}}
$$

Converting the Fahrenheits to Kelvin, and plugging it in:

$$
K_{C} = \frac{294.27}{308.72 - 294.27}
$$

This comes out to be $K_{C} = 20.4$, or to put into words, 20.4 Joules are removed from the room for every 1 joule of electric energy required to operate the air conditioner.

## Question 41

This question is regarding **refrigerators and real engines**.

> An air conditioner operating between $93^{\circ}\text{ F}$ and $70^{\circ}\text{ F}$ is rated at 4000 Btu/h cooling capacity. Its coefficient of performance is 27% of that of a Carnot refrigerator operating between the same two temperatures. What horsepower is required of the air conditioner motor.

Let us determine some steps we can take to find the solution:

* Find the coefficient of performance of a Carnot refrigerator for these conditions
* Determine the coefficient of performance of the air conditioner presented in the question from the coefficient of performance of the Carnot refrigerator
* $P = \frac{W}{t}$. We can rearrange this into $\frac{Q_{L}}{t} * \frac{1}{K}$, as we know $K = \frac{\lvert Q_{L} \rvert}{W}$

Before doing the question, convert the Fahrenheits to Kelvin and the British thermal units per hour to horsepower.

$$
K_{C} = \frac{T_{L}}{T_{H} - T_{L}}
$$

$$
K_{C} = \frac{294.27}{307.05 - 294.27}
$$

Multiply this by $0.27$ for the coefficient of performance for the air conditioner: 

$$
K = 0.27 * \frac{294.27}{307.05 - 294.27}
$$

$K = 6.22$. Now, we can determine the power:

$$
P = \frac{\frac{\lvert Q_{L} \rvert}{K}}{t}
$$

$$
P = \frac{Q_{L}}{t} * \frac{1}{K}
$$

$$
P = \frac{1.56}{6.22}
$$

Our answer comes out to be $P = 0.25\text{ hp}$.

## Question 43

This question is regarding **refrigerators and real engines**. It requires a figure to solve the question.

> Figure 20-32 represents a Carnot engine that works between temperatures $T_{1} = 400 K$ and $T_{2} = 150 K$ and drives a Carnot refrigerator that works between temperatures $T_{3} = 325 K$ and $T_{4} = 225 K$. What is the ratio $Q_{3}$/$Q_{1}$?

First, we know the efficiency of the Carnot engine (or the ratio of the energy we get over what we pay for):

$$
\varepsilon = \frac{T_{1} - T_{2}}{T_{1}}
$$

We also know the coefficient of performance for the Carnot refrigerator:

$$
K = \frac{Q_{4}}{W} = \frac{T_{4}}{T_{3} - T_{4}}
$$

We know the work done is the change in energy, so $Q_{4} + W = Q_{3}$. To put this in terms of $Q_{4}$, $Q_{4} = Q_{3} - W$. This is useful because we know:

$$
K = \frac{T_{4}}{T_{3} - T_{4}} = \frac{Q_{4}}{W}
$$

(The energy we want is $Q_{4}$ [heat energy from cold reservoir to hot reservoir], and the work done is denoted by $W$).

Therefore,

$$
K = \frac{Q_{4}}{W} = \frac{Q_{3} - W}{W} = \frac{Q_{3}}{W} - 1
$$

We know the work done on the refrigerator is driven by the Carnot engine. So we know the work from the efficiency calculation for the Carnot engine is the same as the work for the coefficient of performance for the Carnot refrigerator:

Recall: 

$$
W = Q_{1} * \frac{T_{1} - T_{2}}{T_{1}}
$$

We know that $K = \frac{T_{4}}{T_{3} - T_{4}}$. Thus:

$$
K = \frac{Q_{3} * T_{1}}{Q_{1} * (T_{1} - T_{2})} - 1 = \frac{T_{4}}{T_{3} - T_{4}}
$$

Now, we can solve for $\frac{Q_{3}}{Q_{1}}$:

$$
\frac{Q_{3}}{Q_{1}} = \frac{1 - \frac{T_{2}}{T_{1}}}{1 - \frac{T_{4}}{T_{3}}}
$$

This comes out to be `2.03`.

## Question 46

This question is regarding **microstates**.

> A box contains N identical gas molecules equally divided between its two halves. For N = 50, what are
>
> * the multiplicity W of the central configuration
> * the total number of microstates
> * the percentage of the time the system spends in the central configuration?
> 
> For N = 100, what are
> 
> * W of the central configuration
> * the total number of microstates
> * the percentage of the time the system spends in the central configuration?
>
> For N = 200, what are
>
> * W of the central configuration
> * the total number of microstates
> * the percentage of the time the system spends in the central configuration?
> * Does the time spent in the central configuration increase or decrease with an increase in N?

For $N = 50$, we can determine the multiplicity of the configuration:

$$
\frac{50!}{25! 25!}
$$

This comes out to be $1.264 \times 10^{14}$.

The number of microstates is $2^{50}$, or $1.126 \times 10^{15}$.

The percentage of time spent in the central configuration is given by:

$$
\frac{W}{\text{\# of microstates}} = \frac{1.264 \times 10^{14}}{1.126 \times 10^{15}}
$$

This comes out to be 11.2%

Repeat this for N = 100, and N = 200

N = 100:

* $W = 1 \times 10^{29}$
* $\text{microstates} = 1.268 \times 10^{30}$
* $\text{central configuration time percent} = 7.886%$

N = 200:

* $W = 9.3 \times 10^{58}$
* $\text{microstates} = 1.607 \times 10^{60}$
* $\text{central configuration time percent} = 5.787%$

The time spent in the central configuration is going to decrease as $N$ increases.
