---
title: "Kinetic Theory of Gases"
date: "January 29th, 2021"
output: pdf_document
---

## Formulas

Molar mass

\begin{equation}
    \label{eq:molar_mass}
    M = m N_{A}
\end{equation}

Moles per mass sample

\begin{equation}
    \label{eq:moles_per_mass_sample}
    n = \frac{N}{N_{A}} = \frac{M_{sam}}{M} = \frac{M_{sam}}{m N_{A}}
\end{equation}

Ideal Gas formula

\begin{equation}
    \label{eq:ideal_gas_law}
    pV = nRT
\end{equation}

Where:

* $p$ is the pressure of the gas
* $V$ is the volume of the gas
* $n$ is the number of moles of the gas
* $R$ is known as the gas constant ($8.31$ J/mol * k)
* $T$ is the temperature of the gas

The ideal gas law can also be represented with Boltzmann's constant $k$ if we replace the number of moles with the number of elementary units, $N$.

\begin{equation}
    \label{eq:ideal_gas_law_molecules}
    pV = NkT
\end{equation}

Where:

* $N$ is the number of elementary units
* $k$ is the Boltzmann constant ($1.38 \times 10^{-23}$ J/K)

The work done when volume of an ideal gas changes (and temperature stays constant [isothermal])

\begin{equation}
    \label{eq:isothermal_process_work}
    W = nRT ln ( \frac{V_{f}}{V_{i}} )
\end{equation}

Pressure exerted by $n$ moles of an ideal gas

\begin{equation}
    \label{eq:ideal_gas_pressure}
    p = \frac{n M v^{2}_{rms}}{3V}
\end{equation}

Where:

* $v_{rms} = \sqrt{(v^{2})_{avg}}$, this is the root-mean-squared speed of the gas molecules
* $M$ is the molar mass of the gas
* $V$ is the volume of the gas
* $n$ is the number of moles

RMS (root-mean-squared) speed expressed in terms of temperature and molar mass:

\begin{equation}
    \label{eq:rms_terms_temperature}
    v_{rms} = \sqrt{\frac{3RT}{M}}
\end{equation}

Where:

* $T$ is the temperature of the gas
* $R$ is known as the gas constant ($8.31$ J/mol * k)
* $M$ is the molar mass of the gas

Average translational kinetic energy per molecule in an ideal gas:

\begin{equation}
    \label{eq:translational_kinetic_energy}
    K_{avg} = \frac{1}{2} m v^{2}_{rms}
\end{equation}

Average translational kinetic energy per molecule in an ideal gas _in terms of temperature_:

\begin{equation}
    \label{eq:translational_kinetic_energy_temperature}
    K_{avg} = \frac{3}{2} k T
\end{equation}

Where:

* $k$ is the Boltzmann constant ($1.38 \times 10^{-23}$ J/K)

Mean free path of a molecule (average distance traveled between collisions of a molecule):

\begin{equation}
    \label{eq:mean_free_path}
    \lambda = \frac{1}{\sqrt{2} \pi d^{2} N/V}
\end{equation}

Where:

* $d$ is the diameter of the molecule
* $N/V$ is the number of molecules per unit volume

Sometimes we are interested in the distribution of molecular speeds. The Maxwell speed distribution allows us to do this. It is a function $P(v)$ such that $P(v) dv$ is a fraction of molecules with speeds in the interval $dv$.

\begin{equation}
    \label{eq:maxwell_speed_distribution}
    P(v) = 4 \pi ( \frac{M}{2 \pi RT} )^{\frac{3}{2}} v^{2} e^{\frac{-M v^{2}}{2RT}}
\end{equation}

Based on this distribution, we can find a few speeds of interest relative to the distribution:

The average speed of the distribution is given by

\begin{equation}
    \label{eq:avg_speed_maxwell_dist}
    v_{avg} = \sqrt{\frac{8RT}{\pi M}}
\end{equation}

The most probable speed of the distribution is given by

\begin{equation}
    \label{eq:probable_speed_maxwell_dist}
    v_{p} = \sqrt{\frac{2RT}{M}}
\end{equation}

The RMS speed of the distribution is given by

\begin{equation}
    \label{eq:rms_speed_maxwell_dist}
    v_{rms} = \sqrt{\frac{3RT}{M}}
\end{equation}

Where:

* $R$ is known as the gas constant ($8.31$ J/mol * k)
* $M$ is the molar mass

The molar specific heat $C_{v}$ of a gas at constant volume:

\begin{equation}
    \label{eq:molar_specific_heat}
    C_{v} = \frac{Q}{n \Delta T} = \frac{\Delta E_{int}}{n \Delta T}
\end{equation}

For an ideal monatomic gas:

$$
C_{v} = \frac{3}{2} R = 12.5\text{J/mol * k}
$$

For a gas that is diatomic and molecules that rotate and do not oscillate:

$$
C_{v} = \frac{7}{2} R
$$


Molar specific heat from constant volume to constant pressure

$$
C_{p} = C_{v} + R
$$

Change in internal energy due to temp change of an ideal gas:

\begin{equation}
    \label{eq:work_ideal_gas_deltatemp}
    \Delta E_{int} = n C_{v} \Delta T
\end{equation}

Where:

* $Q$ is the energy transferred as heat to or from a sample of $n$ moles.
* $\Delta T$ is the resulting temperature change from the energy transfer

Molar specific heat based on degrees of freedom:

\begin{equation}
    \label{eq:molar_specific_heat_dof}
    C_{v} = ( \frac{f}{2} ) R
\end{equation}

Notes:

* For monatomic gases, degrees of freedom is 3 and for diatomic gases it is 5.

If an ideal gas goes through a slow adiabatic volume change (such that $Q = 0$), $p V^{\gamma}$ is a constant. Note: $\gamma = \frac{C_{p}}{C_{v}}$ -- this is the ratio of molar specific heats for the gas.

For free expansion, $pV$ is a constant.

## Avogadro's Number

The kinetic theory of gases relates the macroscopic properties of a gas, like its pressure/temperature, to properties of the molecules that make it up.

We say that a **mole** of a substance contains $N_{A}$ elementary units (atoms/molecules). $N_{A}$ experimentally is $6.02 \times 10^{23}\ mol^{-1}$. A molar mass $M$ of a substance is the mass of 1 mole of the substance.

Molar mass is represented by formula \ref{eq:molar_mass}

## Ideal Gases

The pressure, volume, and temperature of a gas are related by formula \ref{eq:ideal_gas_law} if the gas is an ideal gas.

The work done by a gas when its volume changes (and its temperature is constant) is given by formula \ref{eq:isothermal_process_work}.

## Pressure, Temperature, and RMS speed

The pressure an ideal gas exerts is given by \ref{eq:ideal_gas_pressure}

The RMS speed in terms of temperature and molar mass is given by \ref{eq:rms_terms_temperature}

## Translational Kinetic Energy

Molecules move around, so they have kinetic energy. The average translational kinetic energy per molecule in an ideal gas is given by \ref{eq:translational_kinetic_energy}.

## Maxwell Equipartition Theorem

Each degree of freedom contributes $\frac{1}{2} kT$ of internal energy per atom. For monatomic gases this is easy, 3 dimensions, 3 degrees of freedom. For multi-atom molecules you have to consider axis of rotations although so diatomic molecules have 5 degrees of freedom, and polyatomic molecules have 6.

## Problems

## Question 66

> An ideal gas consists of 1.50 mol of diatomic molecules that rotate but do not oscillate. The molecular diameter is 250 pm. The gas is expanded at a constant pressure of $1.50 \times 10^{5}$ Pa, with a transfer of 200 J as heat. What is the change in the mean free path of the molecules?

Won't solve this entirely, but here are the steps:

- Find N, which is easy
- Identify mean free path formula
- Notice we do not have V
- Express V in terms of ideal gas law
- Derivate mean free path formula
- Represent $n \Delta T$ as $\frac{Q}{C_{p}}$
- Notice that $C_{p} = \frac{7}{2} R$ since gas is composed of diatomic molecules that rotate but do not oscillate.
- Find change in mean free path

## Lecture Problem 1

At 273 K and $1.00 \times 10^{-2}$ atm, the density of a gas is $1.24 \times 10^{-5}$ g/$\text{cm}^{3}$.

* Find $v_{rms}$ for the gas molecules
* Find the molar mass of the gas
* Identify the gas

$$
\rho = \frac{m_{sam}}{V}
$$

or

$$
V = \frac{m_{sam}}{\rho}
$$

$$
pV = p \frac{m_{sam}}{\rho} = nRT
$$

$$
\frac{m_{sam}}{n} = M = \frac{\rho R T}{p}
$$

So:

$$
v_{rms} = \sqrt{\frac{3RT}{M}} = \sqrt{\frac{3p}{\rho}} = 494
$$

494m/s

Find molar mass:

$$
M = \frac{\rho RT}{p} = 27.9
$$

27.9 g/mol

Gas must be $N_{2}$

## Problem 2

This question is regarding **Avogadro's number**.

> Gold has a molar mass of 197 g/mol.
> 
> * How many moles of hold are in a 2.50 g sample of pure gold?
> * How many atoms are in the sample

The molar mass tell us how many grams are in a mole of a specific substance. If there are 197 grams per mole of pure gold, we can use this ratio to convert the 2.50g sample into moles using dimensional analysis.

$$
\frac{2.50\text{ g}}{} * \frac{1\text{ mol}}{197\text{ g}} = 0.013\text{ mol}
$$

Our answer is 0.013 moles.

The next part of the question then asks us to determine the number of atoms in the sample. This is simple, as we know Avogadro's number tels us the amount of elementary units (atoms/molecules) for a mole of a substance. Avogadro's number is $6.02 \times 10^{23}$, so we can use this value in a dimensional analysis to figure out the amount of atoms in the substance:

$$
\frac{0.013\text{ mol}}{} * \frac{6.02 \times 10^{23}\text{ atoms}}{1\text{ mol}} = 7.64 \times 10^{21}\text{ atoms}
$$

Our answer is $7.64 \times 10^{21}$ atoms.

## Problem 3

This question is regarding **ideal gases**.

> Oxygen gas having a volume of 1000 $\text{cm}^{3}$ at $40.0^{\circ}\text{ C}$ and $1.01 \times 10^{5}$ Pa expands until its volume is 1500 $\text{cm}^{3}$ and its pressure is $1.06 \times 10^{5}$ Pa. Find:
>
> * the number of moles of oxygen present and 
> * the final temperature of the sample.

For this question, we just need to apply the ideal gas law:

$$
pV = nRT
$$

Converting the temperature to Kelvin and the volume from $\text{cm}^{3}$ to $\text{m}^{3}$, we can find $n$, which is the number of moles. This comes out to be 0.039 moles.

Similarly, we can find the temperature after the gas expands. This comes out to be $493\text{ K}$, or $220^{\circ}\text{ C}$.

## Problem 21

This question is regarding **RMS speed**.

> The lowest possible temperature in outer space is 2.7 K. What is the **rms speed** of hydrogen molecules at this temperature? (The molar mass is given in Table 19-1.)

For this question, we simply need to apply formula \ref{eq:rms_speed_maxwell_dist}. We already know $T$. And, the molar mass of hydrogen molecules is 2.02 g/mol (according to the table). We convert this to kg/mol, and then apply the formula:

$$
v_{rms} = \sqrt{\frac{3 (8.31) 2.7}{2.02 / 1000}} = 182\text{ m/s}
$$

Thus, our answer is 182 m/s.

## Problem 23

This problem is regarding **pressure, temperature, and RMS speed**.

> A beam of hydrogen molecules ($\text{H}_{2}$) is directed toward a wall, at an angle of $55^{\circ}$ with the normal to the wall. Each molecule in the beam has a speed of 1.0 km/s and a mass of $3.3 \times 10^{-24}$ g. The beam strikes the wall over an area of 2.0 $\text{cm}^{2}$, at the rate of $10^{23}$ molecules per second. What is the beam's pressure on the wall?

$$
F = \Delta p
$$

We know how force is related to pressure:

$$
P = \frac{F}{A}
$$

For our problem we will need $\Delta p$ to find the force:

$$
\Delta p = \frac{p}{t}
$$

Solve for $p$:

$$
p = mv
$$

In this case

$$
p_{p} p = 2 mv cos(55)
$$

This is for a single particle (hence $\Delta p_{p}$). There are $10^{23}$ particles in a second.

$$
p = 10^{23} 2 (3.3 \times 10^{-27}) (1000) cos(55)
$$

We know $\Delta t = 1$, so $F = \Delta p = \frac{p}{\Delta t} = p$

We also know the value of $A$.

Coming back to this formula:

$$
P = \frac{F}{A}
$$

$$
P = \frac{10^{23} 2 (3.3 \times 10^{-27}) (1000) cos(55)}{2.0 \times 10^{-4}}
$$

This comes out to be `1.9 kPa`.

Alternatively, we can notice

## Problem 27

This question is regarding **translational kinetic energy**.

> Water standing in the open at $32.0^{\circ}\text{ C}$ evaporates because of the escape of some of the surface molecules. The heat of vaporization (539 cal/g) is approximately equal to $\varepsilon n$, where $\varepsilon$ is the average energy of the escaping molecules and n is the number of molecules per gram.
> 
> * Find $\varepsilon$
> * What is the ratio of $\varepsilon$ to the average kinetic energy of $\text{H}_{2}\text{O}$ molecules, assuming the latter is related to temperature in the same way as it is for gases?

For this question, let us first convert the heat of vaporization into a unit that uses Joules, the SI unit. Note that the molar mass of water is 18 g/mol. We know Avogadro's number, which is $6.02 \times 10^{23}$ molecules/mol. Through dimensional analysis, we notice that diving Avogadro's number by the molar mass gives us the number of molecules in 1 gram of water, which is exactly what we want to start this question. This quantity is $n$ in the expression $\varepsilon n$, and the expression is equal to the heat of vaporization we converted to J/g earlier. So we just divide the heat of vaporization by $n$, and we get our answer: $6.75 \times 10^{-20}$

## Problem 31

This question is regarding **mean free path**.

> In a certain particle accelerator, protons travel around a circular path of diameter 23.0 m in an evacuated chamber, whose residual gas is at 295 K and $1.00 \times 10^{-6}$ torr pressure.
> 
> * Calculate the number of gas molecules per cubic centimeter at this pressure. 
> * What is the mean free path of the gas molecules if the molecular diameter is $2.00 \times 10^{-8}$ cm?

First, let us convert the pressure from torrs into Pascals. After this, we can use the ideal gas law to find the value of $\frac{N}{V}$. First, we need to convert $n$ in the gas law to the number of molecules, $N$. This can be done simply, by multiplying $n$, the number of moles, by Avogadro's number:

$$
pV = nRT
$$

$$
pV = (n * N_{A}) RT
$$

We want to solve for $N / V$. $(n * N_{A})$ is $N$ in this expression.

$$
\frac{N}{V} = \frac{p}{RT} 
$$

This comes out to be $3.27 \times 10^{10}\text{ 1/m}^{3}$.

Now, we can tackle the second part of the question, which is actually pretty straight forward. For this part of the question, we simply use the mean free path $\lambda$ part of the formula to do the calculation:

$$
\lambda = \frac{1}{\sqrt{2} \pi d^{2} \frac{N}{V}}
$$

We have the diameter given to us, and we know the value of $\frac{N}{V}$. We can simply do the calculation from here. This comes out to be 172m.

## Problem 34

This question is regarding **the distribution of molecular speeds**.

> The speeds of 22 particles are as follows [in textbook] ($N_{i}$ represents the number of particles that have speed $v_{i}$)
>
> * What is $v_{avg}$?
> * What is $v_{rms}$?
> * What is $v_{p}$?

To find the average is fairly simple -- sum the speeds and divide by 22:

$$
(2 * 1 + 4 * 2 + 6 * 3 + 8 * 4 + 2 * 5) / 22 = 3.18
$$

Thus, our $v_{avg} = 3.18\text{ m/s}$.

Root mean squared is just the square root of the average of the elements squared:

$$
\sqrt{\frac{((2 * 1^{2}) + (4 * 2^{2}) + (6 * 3^{2}) + (8 * 4^{2}) + (2 * 5^{2}))}{22}} = 3.37
$$

Thus, our $v_{rms} = 3.37\text{ m/s}$.

The most probable speed ($v_{p}$) is 4.0 m/s, the table shows the particles grouped by speed, and the 4.0 group is the biggest.

## Problem 41

This question is regarding **the distribution of molecular speeds**.

> A hydrogen molecule (diameter $1.0 \times 10^{-8}$ cm), traveling at the rms speed, escapes from a 4000 K furnace into a chamber containing _cold_ argon atoms (diameter $3.0 \times 10^{-8}$ cm) at a density of $4.0 \times 10^{19}$ $\text{atoms/cm}^{3}$.
> 
> What is the speed of the hydrogen molecule?
> If it collides with an argon atom, what is the closest their centers can be, considering each as spherical?
> What is the initial number of collisions per second experienced by the hydrogen molecule? (Hint: Assume that the argon atoms are stationary. Then the mean free path of the hydrogen molecule is given by Eq. 19-26 and not Eq. 19-25.)

To find the speed of the hydrogen molecule, we just find the rms speed:

$$
\sqrt{\frac{3 * 8.31 * 4000}{2.02 / 1000}}
$$

This comes out to be 7026 m/s.

The next part of the question asks us the distance of separation when the atoms are closest together upon collision. This would just be the radius of the argon atom and the radius of the hydrogen molecule added together:

$$
\frac{1.0 \times 10^{-8}}{2} + \frac{3.0 \times 10^{-8}}{2}
$$

This comes out to be $2.0 \times 10^{-8}\text{ cm}$

Finally, we are asked for the initial number of collisions per second experienced by the hydrogen molecule. To determine this, we can use the mean free path. After finding the mean free path, we can divide the speed by the mean free path to determine how many collisions there will be, as the mean free path tells us the path length _between_ collisions.

The book hints to use formula 19-26:

$$
\frac{1}{\pi (2.0 \times 10^{-8}\text{ cm})^{2} * (4.0 \times 10^{19})}
$$

After finding this, we can then divide the speed by it for our answer:

$$
\frac{7026 * 100}{1.98 \times 10^{-5}}
$$

This comes out to be $3.5 \times 10^{10}$ collisions.

## Problem 49

This question is regarding **the molar specific heats of ideal gases**.

> A container holds a mixture of three nonreacting gases: 2.40 mol of gas 1 with $C_{V1}$ = 12.0 J/mol * K, 1.50 mol of gas 2 with $C_{V2}$ = 12.8 J/mol * K, and 3.20 mol of gas 3 with $C_{V3}$ = 20.0 J/mol * K. What is $C_{V}$ of the mixture?

For this question, let us first find the heat capacity for each of the gases given their molar specific heats and their mole amounts. We will sum them up after finding them:

$$
(2.40 * 12) + (1.50 * 12.8) + (3.20 * 20.0) = 112
$$

The heat capacity of the mixture is 112 J/K. From here, we can just divide by the number of moles in the mixture (which is just the sum of those), and we will have the molar specific heat of the mixture.

$$
\frac{112}{2.4 + 1.5 + 3.2} = 15.8
$$

Thus, our answer is $C_{v} = 15.8\text{ J / mol * K}$

## Problem 53

This question is regarding **degrees of freedom and molar specific heats**.

> Suppose 4.00 mol of an ideal diatomic gas, with molecular rotation but not oscillation, experienced a temperature increase of 60.0 K under constant-pressure conditions. What are:
> 
> the energy transferred as heat Q
> the change $\Delta E_{int}$ in internal energy of the gas
> the work W done by the gas
> the change $\Delta K$ in the total translational kinetic energy of the gas?

To find $Q$, we can use $Q = n C_{p} \Delta T$:

Since the gas is diatomic, and the molecules rotate but don't oscillate, the molar specific heat is given by $C_{p} = \frac{7}{2} R$.

$$
Q = \frac{7}{2} R n \Delta T
$$

$$
Q = \frac{7}{2} * 8.31 * 4.00 * 60 = 6980 J
$$

Thus, our answer for part a is 6980 J.

Part B asks us for the internal energy of the gas. Well, we already have $Q$, and from the first law of thermodynamics we can determine we just need to find $-W$ to find the change in internal energy. We can use the ideal gas law here, since we know $W = nR \Delta T$. Thus:

$$
\Delta E_{int} = Q - W
$$

$$
\Delta E_{int} = (\frac{7}{2} n R \Delta T) - (n R \Delta T) = \frac{5}{2} n R \Delta T = 4986 J
$$

Thus, our answer for part b is 4986 J.

Part C asks us for the work done by the gas. We just calculated this for part B: $n R \Delta T = 1994 J$.

Thus, our answer is 1994 J.

Part D asks us for the total change in **translational** kinetic energy of the gas. We can determine the molar specific heat for constant pressure conditions:

$$
C_{p} = \frac{5}{2} * R
$$

This is because we are under constant pressure conditions, and only considering the translational motion, so we have 5 degrees of freedom.

We know that $\Delta K = \Delta E_{int}$:

$$
\Delta K = Q - W
$$

$$
\Delta K = (C_{p} * n * R * \Delta T) - (n * R * \Delta T) = (C_{p} - 1) * n R T
$$

$$
(C_{p} - 1) * n R T = (\frac{5}{2} - \frac{2}{2}) * 4 * 8.31 * 60 = 2991 J
$$

Thus, our answer is 2991 J.
