---
title: "Interference"
date: "February 11th, 2021"
output: pdf_document
---

## Formulas

_Light as a wave_

Index of refraction of a medium can be found by:

$$
n = \frac{c}{v}
$$

Where:

* $n$ is the index of refraction
* $c$ is the speed of light in vacuum
* $v$ is the speed of light in the medium

The wavelength of light in a medium depends on the index of refraction $n$ of the medium:

$$
\lambda_{n} = \frac{\lambda}{n}
$$

Where:

* $\lambda$ is the wavelength in vacuum

Since wavelength depends on index of refraction, phase difference can change due to medium.

_Young's Interference Experiment_

To find the maximum intensity of an interference for Young's experiment:

$$
d = sin \theta = m \lambda
$$

Minimum intensity:

$$
d = sin \theta = (m + \frac{1}{2}) \lambda
$$

Where:

* $m$ is 0, 1, 2...
* $d$ is the slit separation
* $\lambda$ is the wavelength$

In Young's interference experiment, two waves of intensity $I_{0}$ will yield a resulting wave of intensity $I$ at the viewing screen:

$$
I = 4 I_{0} cos^{2} \frac{1}{2} \phi
$$

Where:

* $\phi = \frac{2 \pi d}{\lambda} sin \theta$

Maxima for light incident on a thin transparent film (bright film in air):

$$
2L = (m + \frac{1}{2} ) \frac{\lambda}{n_{2}}
$$

Minima (dark film in air):

$$
2L = m \frac{\lambda}{n_{2}}
$$

Where:

* $n_{2}$ is the index of refreaction of the film
* $L$ is the thickness of the film
* $\lambda$ is the wavelength of the light in air

Phase difference of recombining beams (Michelson's Interferometer):

$$
\text{phase difference} = \frac{2L}{\lambda} (n - 1)
$$

Where:

* $n$ is the index of refraction of the transparent material
* $L$ is the thickness of one path
* $\lambda$ is the wavelength of light

## Lecture Notes

$$
\lambda_{n_{i}} = \frac{\lambda}{n_{i}}
$$

$$
N_{2} - N_{1}
$$

The result of this number, if an integer, means there is no phase difference, as $N_{1}$ and $N_{2}$ are the number of wavelengths.

Diffraction is the flaring out of waves through slits, Young did an experiment to prove light is a wave.

Young had a single slit which light passed through -- the wave produced wavelets through the slits, and then he had two slits, so two sources of wavelets What was produced was maxima and minima (fringes) of light. This is because the two wavelets interfered.

The fact that light in interferes that lights are waves.

In phase are maximia, out of phase are minima.

$$
\lambda \approx \frac{yd}{D}
$$

Where:

* $d$ is the distance between the slits
* $D$ is the distance between the slits and the surface

## Problems

## Problem 1

This question is regarding **light as a wave**.

> In fig. 35-31, a light wave along ray $r_{1}$ reflects once from a mirror and a light wave along ray $r_{2}$ reflects twice from that same mirror and once from a tiny mirror at a distance $L$ from the bigger mirror. (Neglect the slight tilt of the rays.) The waves have wavelength 620 nm and are initially in phase.
>
> * What is the smallest value of $L$ that puts the final light waves exactly out of phase?
> * With the tiny mirror initially at that value of $L$, how far must it be moved away from the biggest mirror to again put the final waves of phase?

The waves are exactly out of phase when they are half a wavelength out of phase (completely destructive). So, this is going to be when L is $\frac{\lambda}{4}$. This is because the waves reflects off the small mirror, and then reflects off of the big mirror. This adds up to a phase diff of $\frac{\lambda}{2}$ (since it traveled $2L$), which will put it it exactly out of phase.

$$
L = \frac{620}{4}
$$

Thus, our answer is $155$ nm.

Now, for the second question, it is kind of weirdly worded. It says that it is initially at the value of $L$, but referring to the value we used in part a. This is important to note, because in a we at a quarter of a wavelength. The next value of $L$ that would put it out of phase is $\frac{3 \lambda}{4}$ since this would result in a phase difference of $\frac{3}{2}$ wavelengths, which is completely out of phase.

The question asks us how far it has to be moved away from the $L$ value of part a. Thus our answer is $\frac{3 \lambda}{4} - \frac{\lambda}{4} = \frac{\lambda}{2}$. Our answer is $310$ nm.

## Problem 6

This question is regarding **light as a wave**.

> The wavelength of yellow sodium light in air is 589 nm.
>
> * What is its frequency?
> * What is the wavelength in glass whose index of refraction is 1.52?
> * From the results of (a) and (b), find its speed in this glass.

Frequency we can find using $f = \frac{c}{\lambda} = \frac{3 \times 10^{8}}{589 \times 10^{-9}}$. This comes out to be $5.09 \times 10^{14}$ Hz, our answer.

We can find the wavelength in glass using $\lambda_{n} = \frac{\lambda}{n} = \frac{589\text{ nm}}{1.52}$. This comes out to be $387.5$ nm, our answer.

Finally, we need to find its speed in the glass. We know that $v = \lambda f$. We have both the frequency of the wave and its wavelength in the glass medium, so our answer is $5.09 \times 10^{14} * 387.5 \times 10^{-9}$, which comes out to be $1.97 \times 10^{8}$ m/s.

## Problem 19

This question is regarding **Young's interference experiment**.

> Suppose that Young's experiment is performed with blue-green light of wavelength 500 nm. The slits are 1.20 mm apart, and the viewing screen is 5.40 m from the slits. How far apart are the bright fringes near the center of the interference pattern?

We can find the sine of the angle made by the slit separation and the line perpendicular to the parallel rays. This is because the path length difference can be represented as $m \lambda$, and thus we can determine the ratio between the path length difference and slit separation:

$$
sin \theta = \frac{\lambda}{d}
$$

Now, through the small angle approximation, we know that $sin \theta \approx \theta$ and $tan \theta \approx \theta$, thus $sin \theta \approx tan \theta$. The reason this is important is because we can utilize the tangent to find the distance between two maxima fringes:

$$
D sin \theta \approx D tan \theta
$$

$y = D tan \theta$ because of trigonometry:

$$
D (\frac{\lambda}{d})
$$

This comes out to be 2.25 mm, our answer.

## Question 23

This question is regarding **Young's interference experiment**.

> In Fig. 35-38, sources A and B emit long-range radio waves of wavelength 400 m, with the phase of the emission from A ahead of that from source B by $90^{\circ}$. The distance $r_{A}$ from $A$ to detector $D$ is greater than the corresponding distance $r_{B}$ by 100m. What is the phase difference of the waves at $D$?

For this question we need to find the net phase difference. First, we know that A is leading by 90 degrees, or a fourth of the wavelength. However, we know that it has to travel an extra 100 meters, which is a fourth of the 400 meter wavelength. This amounts to a **net phase difference of 0**, our answer.

$$
\frac{\lambda}{4} - \frac{\lambda}{4} = 0
$$

## Problem 29

This question is regarding **interference and double-slit intensity**.

> Two waves of the same frequency have amplitudes 1.00 and 2.00. They interfere at a point where their phase difference is $60.0^{\circ}$. What is the resultant amplitude?

For this question, we can use phasors to solve it. We represent the waves with magnitudes representing their amplitudes. We know the angle between the two waves/phasors is going to be 60 degrees. We can choose an arbitrary point to lay the first phasor, which I would do at the x axis. So, we can find the sum of the vectors by finding the x and y components and then using Pythagorean theorem:

X component:

$$
1 * cos(0) + 2 * cos(60)
$$

Y component:

$$
1 * sin(0) + 2 * sin(60)
$$

Then, we can find the hypotenuse using Pythagorean theorem:

$$
\sqrt{(1 * cos(0) + 2 * cos(60)) + (1 * sin(0) + 2 * sin(60))}
$$

$$
\sqrt{(1 + 2 * cos(60)) + (0 + 2 * sin(60))}
$$

This comes out to be `2.65`, our answer.

## Problem 37

This problem is regarding **interference from thin films**.

> The rhinestones in costume jewelry are glass with index of refraction 1.50. To make them more reflective, they are often coated with a layer of silicon monoxide of index of refraction 2.00. What is the minimum coating thickness needed to ensure that light of wavelength 560 nm and of perpendicular incidence will be reflected from the two surfaces of the coating with fully constructive interference?

We want to find the maxima for light incident on a transparent film:

$$
2L = (m + \frac{1}{2}) \frac{\lambda}{n_{2}}
$$

We use $m = 0$ to minimize the thickness

$$
(\frac{1}{2}) * \frac{560}{2}
$$

$$
\frac{560}{4}
$$

Thus, our answer is 70nm.

## Problem 40

This problem is regarding **interference from thin films**.

> A thin film of acetone (n = 1.25) coats a thick glass plate (n = 1.50). White light is incident normal to the film. In the reflections, fully destructive interference occurs at 600nm and fully constructive interference at 700 nm. Calculate the thickness of the acetone film.

Interchange maxima/minima equations since the acetone film has a lower index of refraction than the next layer which is the glass plate.

So, for the minima:

$$
2L = ( m + \frac{1}{2} ) \frac{\lambda}{n_{2}}
$$

$$
2L = ( m + \frac{1}{2} ) \frac{600}{1.25}
$$

For values of $m$ 0, 1, 2, 3, L is: 120, 360, 600, 840

Now, for the maxima:

$$
2L = ( m ) \frac{\lambda}{n_{2}}
$$

$$
2L = ( m ) \frac{700}{1.25}
$$

For values of $m$ 1, 2, 3, 4, L is: 280, 560, 840, and 1120

Both sets of values for $m$ have 840, which is the lowest common value between the sets. Thus, 840 nm is our answer

## Problem 79

This problem is regarding **Michelson's Interferometer**.

> If mirror $M_{2}$ in a Michelson interferometer (Fig. 35-21) is moved through 0.233 mm, a shift of 792 bright fringes occurs. What is the wavelength of the light producing the fringe pattern?

For this question, we can find $\lambda$, the wavelength of the light, using:

$$
N_{a} = \frac{2L}{\lambda}
$$

$$
\lambda = \frac{2L}{N_{a}}
$$

$$
\lambda = \frac{2 (0.233)}{792}
$$

This comes out to be 588 nm.

## Problem 81

This problem is regarding **Michelson's Interferometer**.

> In Fig. 35-48, an airtight chamber of length $d = 5.0\text{ cm}$ is placed in one of the arms of a Michelson interferometer. (The glass window on each end of the chamber has negligible thickness.) Light of wavelength $\lambda = 500$ nm is used. Evacuating the air from the chamber causes a shift of 60 bright fringes. From these data and to six significant figures, find the index of refraction of air at atmospheric pressure.

For this question, we can find the index of refraction by using the phase difference formula, namely:

$$
\text{phase difference} = \frac{2L}{\lambda} (n - 1)
$$

We rearrange this for $n$:

$$
n = \frac{\text{phase difference} * \lambda}{2L} + 1
$$

$$
n = \frac{60 * (500 \times 10^{-9})}{2 * .05} + 1
$$

This comes out to be 1.0003, our answer.
